package main

import "github.com/davyxu/gosproto/meta"

const sprotoCodeTemplate = `# Generated by github.com/davyxu/gosproto/sprotogen
# DO NOT EDIT!

{{range .Structs}}
.{{.Name}} {
	{{range .StFields}}
	{{.Name}} {{.TagNumber}} : {{.CompatibleTypeString}}
	{{end}}
}
{{end}}

`

func gen_sproto(fileset *meta.FileDescriptorSet, filename string) {

	fm := &fileModel{
		FileDescriptorSet: fileset,
	}

	addData(fm, "sproto")

	generateCode("sp->sproto", sprotoCodeTemplate, filename, fm, nil)

}
