package main

import "github.com/davyxu/gosproto/meta"

const sprotoCodeTemplate = `# Generated by github.com/davyxu/gosproto/sprotogen
# DO NOT EDIT!

{{range .Structs}}
.{{.Name}} {
	{{range .Fields}}	
	{{.Name}} {{.Tag}} : {{.CompatibleTypeString}}
	{{end}}
}
{{end}}

`

type spFileModel struct {
	*meta.FileDescriptor
}

func gen_sproto(fileD *meta.FileDescriptor, filename string) {

	generateCode("sp->sproto", sprotoCodeTemplate, filename, &spFileModel{
		FileDescriptor: fileD,
	}, nil)

}
