// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!
// Source: test.sproto

package exsample

import (
	"reflect"
)

// test.sproto

type PhoneNumber struct {
	Number string `sproto:"string,0,name=Number"`

	Type int `sproto:"integer,1,name=Type"`
}

type Person struct {
	Name string `sproto:"string,0,name=Name"`

	Id int `sproto:"integer,1,name=Id"`

	Email string `sproto:"string,2,name=Email"`

	Phone []*PhoneNumber `sproto:"struct,3,array,name=Phone"`
}

type AddressBook struct {
	Person []*Person `sproto:"struct,0,array,name=Person"`
}

type MyData struct {
	Name string `sproto:"string,0,name=Name"`

	Type int `sproto:"integer,1,name=Type"`

	Int32 int32 `sproto:"integer,2,name=Int32"`
}

type MyProfile struct {
	NameField *MyData `sproto:"struct,1,name=NameField"`

	NameArray []*MyData `sproto:"struct,2,array,name=NameArray"`

	NameMap []*MyData `sproto:"struct,3,array,name=NameMap"`
}

var SProtoStructs = []reflect.Type{
	// test.sproto
	reflect.TypeOf((*PhoneNumber)(nil)).Elem(),
	reflect.TypeOf((*Person)(nil)).Elem(),
	reflect.TypeOf((*AddressBook)(nil)).Elem(),
	reflect.TypeOf((*MyData)(nil)).Elem(),
	reflect.TypeOf((*MyProfile)(nil)).Elem(),
}
